macro(ntt_setup)
    set(NTT_OPTIONS)
    set(NTT_COMPILE_FLAGS)
    set(NTT_LINK_FLAGS)
    ntt_platform_detect()

    # build profile options
    option(CMAKE_BUILD_TYPE "Choose the type of build." "Debug")

    if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_BUILD_TYPE STREQUAL "")
        set(NTT_DEBUG ON)
        list(APPEND NTT_OPTIONS "NTT_DEBUG")
        list(APPEND NTT_COMPILE_FLAGS "-g" "-fno-omit-frame-pointer" "-O0")
        list(APPEND NTT_LINK_FLAGS "-rdynamic" "-no-pie")
        set(CMAKE_POSITION_INDEPENDENT_CODE ON)
    elseif (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(NTT_RELEASE ON)
        list(APPEND NTT_OPTIONS "NTT_RELEASE")
    elseif (CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
        set(NTT_RELWITHDEBINFO ON)
        list(APPEND NTT_OPTIONS "NTT_RELWITHDEBINFO")
    else()
        message(WARNING "Unknown build type: ${CMAKE_BUILD_TYPE}, defaulting to Debug")
        set(NTT_DEBUG ON)
        list(APPEND NTT_OPTIONS "NTT_DEBUG")
    endif()
endmacro()

macro(ntt_platform_detect)
    if (WIN32)
        set(NTT_PLATFORM_WINDOWS ON)
        list(APPEND NTT_OPTIONS "NTT_PLATFORM_WINDOWS")
    elseif (UNIX)
        set(NTT_PLATFORM_UNIX ON)
        list(APPEND NTT_OPTIONS "NTT_PLATFORM_UNIX")
        list(APPEND NTT_COMPILE_FLAGS 
                "-Wall" 
                "-Wextra" 
                "-Wpedantic" 
                "-Werror")
    else()
        message(FATAL_ERROR "Unsupported platform")
    endif()
endmacro()

macro(ntt_option name)
    option(${name} "Enable ${name}" OFF)
    list(APPEND NTT_OPTIONS ${name})
endmacro()

macro(ntt_option_with_value name value)
    option(${name} "The ${name} with default value ${value}" ${value})
    list(APPEND NTT_OPTIONS ${name})
endmacro()

macro(ntt_log_options)
    message("NTT Configuration Options:")
    foreach(option IN LISTS NTT_OPTIONS)
        if (${${option}})
            message("   - ${option}=1")
        else()
            message("   - ${option}=0")
        endif()
    endforeach()
endmacro()

function(attach_options target)
    foreach(option IN LISTS NTT_OPTIONS)
        if (${${option}})
            target_compile_definitions(${target} PRIVATE ${option}=1)
        else()
            target_compile_definitions(${target} PRIVATE ${option}=0)
        endif()
    endforeach()
endfunction()

function(attach_flags target)
    target_compile_options(${target} PRIVATE ${NTT_COMPILE_FLAGS})
    target_link_libraries(${target} PRIVATE ${NTT_LINK_FLAGS})
endfunction()