macro(ntt_setup)
    set(NTT_OPTIONS)
    ntt_platform_detect()
endmacro()

macro(ntt_platform_detect)
    if (WIN32)
        set(NTT_PLATFORM_WINDOWS ON)
        list(APPEND NTT_OPTIONS "NTT_PLATFORM_WINDOWS")
    elseif (UNIX)
        set(NTT_PLATFORM_UNIX ON)
        list(APPEND NTT_OPTIONS "NTT_PLATFORM_UNIX")
    else()
        message(FATAL_ERROR "Unsupported platform")
    endif()
endmacro()

macro(ntt_option name)
    option(${name} "Enable ${name}" OFF)
    list(APPEND NTT_OPTIONS ${name})
endmacro()

macro(ntt_option_with_value name value)
    option(${name} "The ${name} with default value ${value}" ${value})
    list(APPEND NTT_OPTIONS ${name})
endmacro()

macro(ntt_log_options)
    message("NTT Configuration Options:")
    foreach(option IN LISTS NTT_OPTIONS)
        if (${${option}})
            message("   - ${option}=1")
        else()
            message("   - ${option}=0")
        endif()
    endforeach()
endmacro()

function(attach_options target)
    foreach(option IN LISTS NTT_OPTIONS)
        if (${${option}})
            target_compile_definitions(${target} PRIVATE ${option}=1)
        else()
            target_compile_definitions(${target} PRIVATE ${option}=0)
        endif()
    endforeach()
endfunction()