macro(ntt_setup)
    set(NTT_OPTIONS)
    ntt_platform_detect()
endmacro()

macro(ntt_platform_detect)
    if (WIN32)
        set(NTT_PLATFORM_WINDOWS ON)
        list(APPEND NTT_OPTIONS "NTT_PLATFORM_WINDOWS=1")
    elseif (UNIX)
        set(NTT_PLATFORM_UNIX ON)
        list(APPEND NTT_OPTIONS "NTT_PLATFORM_UNIX=1")
    else()
        message(FATAL_ERROR "Unsupported platform")
    endif()
endmacro()

macro(ntt_option name)
    list(APPEND NTT_OPTIONS "${name}=1")
endmacro()

macro(ntt_log_options)
    message("NTT Configuration Options:")
    foreach(option IN LISTS NTT_OPTIONS)
        message("   - ${option}")
    endforeach()
endmacro()

function(attach_options target)
    foreach(option IN LISTS NTT_OPTIONS)
        target_compile_definitions(${target} PRIVATE ${option})
    endforeach()
endfunction()