#ifndef ENUM_OPTION
#define ENUM_OPTION(option)
#endif

#ifndef ENUM_OPTION_END
#define ENUM_OPTION_END()
#endif

ENUM_OPTION(TRACE)
ENUM_OPTION(DEBUG)
ENUM_OPTION(INFO)
ENUM_OPTION(WARN)
ENUM_OPTION(ERROR)
ENUM_OPTION(FATAL)
ENUM_OPTION_END()
