#ifndef ENUM_OPTION
#define ENUM_OPTION(option)
#endif

#ifndef ENUM_OPTION_END
#define ENUM_OPTION_END()
#endif

ENUM_OPTION(ENGINE)
ENUM_OPTION(CORE)
ENUM_OPTION(DRIVER)
ENUM_OPTION(RESOURCE)
ENUM_OPTION_END()