#ifndef ENUM_OPTION
#define ENUM_OPTION(option)
#endif /* ENUM_OPTION */

#ifndef ENUM_OPTION_END
#define ENUM_OPTION_END(option)
#endif /* ENUM_OPTION_END */

ENUM_OPTION(GLFW)
// ENUM_OPTION(SDL)
// ENUM_OPTION(WIN32)
// ENUM_OPTION(X11)
ENUM_OPTION_END(COUNT)
