#ifndef ENUM_OPTION
#define ENUM_OPTION(option)
#endif

#ifndef ENUM_OPTION_END
#define ENUM_OPTION_END(name)
#endif

ENUM_OPTION(NTT_COLOR_BLACK)
ENUM_OPTION(NTT_COLOR_WHITE)
ENUM_OPTION(NTT_COLOR_RED)
ENUM_OPTION(NTT_COLOR_GREEN)
ENUM_OPTION(NTT_COLOR_BLUE)
ENUM_OPTION(NTT_COLOR_YELLOW)
ENUM_OPTION(NTT_COLOR_CYAN)
ENUM_OPTION(NTT_COLOR_MAGENTA)
ENUM_OPTION(NTT_COLOR_GRAY)
ENUM_OPTION_END(NTT_COLOR_COUNT)