#ifndef ENUM_OPTION
#define ENUM_OPTION(name)
#endif

#ifndef ENUM_END
#define ENUM_END(name)
#endif

ENUM_OPTION(NTT_OBJECT_TYPE_NONE)
ENUM_OPTION(NTT_OBJECT_TYPE_OBJECT_ID)
ENUM_OPTION(NTT_OBJECT_TYPE_OBJECT)
ENUM_END(NTT_OBJECT_TYPE_COUNT)
